import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import React from "react";
import { useSession, signIn, signOut } from "next-auth/react";

const HomeContents = () => {
    const { data: session, status } = useSession();

    if (status === "loading") {
        return <div>Loading...</div>;
    }

    if (!session)
        return (
            <div>
                <div>Please log in</div>
                <button onClick={() => signIn("twitch")}>
                    Sign in with Twitch
                </button>
            </div>
        );

    return (
        <div className="flex flex-col">
            <div>Hello {session.user?.name}!</div>
            <button onClick={() => signOut()}>Sign out</button>
        </div>
    );
};

const Home: NextPage = () => {
    const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);

    return (
        <>
            <Head>
                <title>Stream Q&A Tool</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <HomeContents />
        </>
    );
};

export default Home;
